 
###  numerical python which is also knuow as numpy . it have a concept called numpy which is basically 50 x faster than traditional python list. it was created in 2005 by a developer called travis oliphant , it was widely for the speed and data consistency
    


# libriry numpy 
 - numpy stand for numerical python
 - it is used for numerical computation
 - it uses nd arrays for numerical computations
 - it is the basic foundation of all the  labraries 

In [3]:
import numpy as np

# why we use numpy ?
 - in python we have list that serve as the purpose arrays, but they are slow to slow 

In [4]:
arr = np.array ([234,345,345,])
print(arr)

[234 345 345]


In [6]:
import numpy as np

In [7]:
arr = np.array ([234,345,345])
print(arr.ndim)


1


In [2]:
import numpy as np

## numpy slicing

In [8]:
arr3 = np.array([[12,23,45],[23,34,65],[21,77,37]])
print(arr3[1][2])

65


In [9]:
ar3 = np.array([1,2,3,4,54,6,4,887,22,34,66,88,54,68,34,6])
print(ar3[3:7])
print(ar3[3:])
print(ar3[0:12:2])
print(ar3[::-2])

[ 4 54  6  4]
[  4  54   6   4 887  22  34  66  88  54  68  34   6]
[ 1  3 54  4 22 66]
[  6  68  88  34 887   6   4   2]


## statical operation

In [5]:
stf = np.array( [1,2,3,4,54,6,4,887,22,34,66,88,54,68,34,65])
print(np.max(stf))  #maximum value
print(np.mean(stf))  #average value
print(np.min(stf))  #minimum value
print(np.sum(stf))  #sum of all item
print(np.median(stf))  #middle value

887
87.0
1
1392
34.0


## mathamatical operation

In [10]:
ar1 = np.array([8,7,6])
ar2 = np.array([10,11,12])
np.add(ar1,ar2)

array([18, 18, 18])

In [11]:
np.subtract(ar1,ar2)

array([-2, -4, -6])

In [12]:
np.multiply(ar1,ar2)

array([80, 77, 72])

In [13]:
np.divide(ar1,ar2)

array([0.8       , 0.63636364, 0.5       ])

In [14]:
print(np.power(ar1,2))

[64 49 36]


In [15]:
print(np.sqrt(ar2))

[3.16227766 3.31662479 3.46410162]


In [21]:
#silling and the power of single digit whic is in the list
print(np.power(ar1[2],2))

36
